birds_eye/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

birds_eye/birds_eye/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks", views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),

    # Events --> Calendar, Posts --> Feed | Expected to finish later on. Uncomment when done.
    path("events/", include("events.urls", namespace="events")),
    path("feeds/", include("feeds.urls", namespace="feeds")),
    
    path("clubs/", include("clubs.urls")),
    path('surveys', include('djf_surveys.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

birds_eye/clubs/urls.py
from django.urls import path
from . import views

app_name = "clubs"

urlpatterns = [
    path('', views.ClubListView.as_view(), name="all"),
    path('<int:pk>/', views.ClubDetailView.as_view(), name="club-detail"),
]

birds_eye/events/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.EntireCalendar.as_view(), name="entire"),
]

birds_eye/feeds/urls.py
from django.urls import path
from . import views

app_name = "feeds"

urlpatterns = [
    path("", views.ListFeeds.as_view(), name="all"),
]

birds_eye/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

birds_eye/clubs/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

class Member(models.Model):
    name = models.CharField(max_length=200, verbose_name="Student Name", help_text="Enter the student name")
    id = models.IntegerField(primary_key=True, verbose_name="Student ID", help_text="ID of the student")

    def __int__(self):
        return self.id

class Club(models.Model):
    name = models.CharField(max_length=100, unique=True)
    id = models.AutoField(primary_key=True)
    slogan = models.TextField(max_length=70)
    description = models.TextField(blank=True, null=True)
    member = models.ManyToManyField(Member, help_text="Select a student to join the club")

    class Meta:
        ordering = ['name', 'slogan']

    def display_member(self):
        return ', '.join([member.name for member in self.member.all()[:3]])

    display_member.short_description = "Member"

    def get_absolute_url(self):
        return reverse('clubs:club-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

birds_eye/events/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    pass

birds_eye/feeds/models.py
from django.db import models

# Create your models here.
class Feed(models.Model):
    pass

birds_eye/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreationForm(UserCreationForm):

    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display Name"
        self.fields["email"].label = "Email Address"

birds_eye/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

birds_eye/birds_eye/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

birds_eye/clubs/views.py
from django.shortcuts import render

# Create your views here.
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from clubs.models import Club, Member

class ClubListView(generic.ListView):
    model = Club
    paginate_by = 5

class ClubDetailView(generic.DetailView):
    model = Club

birds_eye/events/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.views import generic 
from django.shortcuts import get_object_or_404
from events.models import Event
from . import models

class EntireCalendar(generic.ListView):
    model = Event

birds_eye/feeds/views.py
from django.shortcuts import render

# Create your views here.
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.views import generic 
from django.shortcuts import get_object_or_404
from feeds.models import Feed
from . import models

class ListFeeds(generic.ListView):
    model = Feed

birds_eye/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    <h1>Log In</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Log In">
    </form>
</div>
{% endblock %}

birds_eye/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Log In">
    </form>
</div>
{% endblock %}

birds_eye/clubs/templates/clubs/club_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% block pregroup %}
    {% endblock %}
    {% block group_content %}
    {% endblock %}
    {% block pagination %}
    {% endblock %}
    {% block postgroup %}
    {% endblock %}
</div>
{% endblock %}

birds_eye/clubs/templates/clubs/club_detail.html
{% extends "clubs/club_base.html" %}
{% load render_table from django_tables2 %}

{% block pregroup %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'clubs:all' %}"><i>'Igniting the spark of genius in every child' - Dwight School Seoul</i></a>
            {% comment %} <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Edit</a>
                    </li>
                </ul>
            </div> {% endcomment %}
        </div>
    </nav>
</div>
<hr>
<div class="container">
    <div class="d-flex flex-row flex-container">
    <div class="p-2 image-box">
        <svg xmlns="http://www.w3.org/2000/svg" width="125" height="125" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
    </div>
    <div class="p-2 description-box">
        <h2>{{ club.name }}</h2>
        <p style="font-size: 24px;">{{ club.slogan|safe }}</p>
        <p>{{ club.description|safe }}</p>
    </div>
    </div>
</div>
{% endblock %}
{% block group_content %}
{% comment %} Work on completing this page!!!! {% endcomment %}
<nav class="navbar navbar-light bg-light" aria-label="First navbar example">
  <div class="container-fluid">
    <a class="navbar-brand text-dark" href="#">Information</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarsExample01">
      <ul class="navbar-nav me-auto mb-2">
        <li class="nav-item">
          <a class="nav-link active text-dark" aria-current="page" href="#">Members</a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link active text-dark" aria-current="page" href="#">Portfolio</a>
        </li> {% endcomment %}
      </ul>
      {% comment %} <form role="search">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form> {% endcomment %}
    </div>
  </div>
</nav>
{% endblock %}
{% block postgroup%}
<br>
<div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">ID</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <!--<th scope="row">1</th>-->
        <!--<td>John</td>-->
        <!--<td>1234567</td>-->
      </tr>
      <tr>
        <!--<th scope="row">2</th>-->
        <!--<td>Jane</td>-->
        <!--<td>9876543</td>-->
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

birds_eye/clubs/templates/clubs/club_list.html
{% extends "clubs/club_base.html" %}

{% block pregroup%}
<div class="col-md-4">
    <div class="container">
        {% if user.is_authenticated %}
        <h2>
            Welcome back!
            <a href="#">
            {% comment %} <a href="{% url 'posts:for_user' username=user.username %}"> {% endcomment %}
                @{{ user.username }}
            </a>
        </h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>

    {% if user.is_authenticated %}
    <a href="{% url 'djf_surveys:index' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign">Create new Group!</span>
    </a>
    {% endif %}

</div>
<hr>
{% endblock %}
{% block group_content %}
<hr>
{% comment %} Complete making group display. {% endcomment %}
<p></p>
<div class="col-md-8">
    <div class="container">
        {% for club in club_list %}
        <a class="list-group-item" href="{{ club.get_absolute_url }}">
            <h3 class="title list-group-item-heading">{{ club.name }}</h3>
            <span>{{ club.slogan|safe }}</span>
        </a>
        <p></p>
        <br>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block pagination %}
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

         Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

{% endblock %}

birds_eye/clubs/templates/clubs/group_detail.html
{% extends "clubs/club_base.html" %}

{% block pregroup %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'clubs:all' %}"><i>'Igniting the spark of genius in every child' - Dwight School Seoul</i></a>
            {% comment %} <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Edit</a>
                    </li>
                </ul>
            </div> {% endcomment %}
        </div>
    </nav>
</div>
<hr>
<div class="container">
    <div class="d-flex flex-row flex-container">
    <div class="p-2 image-box">
        <svg xmlns="http://www.w3.org/2000/svg" width="125" height="125" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
    </div>
    <div class="p-2 description-box">
        <h2>{{ group.name }}</h2>
        <p style="font-size: 24px;">{{ group.slogan|safe }}</p>
        <p>{{ group.description|safe }}</p>
    </div>
    </div>
</div>
{% endblock %}
{% block group_content %}
{% comment %} Work on completing this page!!!! {% endcomment %}
<nav class="navbar navbar-light bg-light" aria-label="First navbar example">
    <div class="container-fluid">
      <a class="navbar-brand text-dark" href="#">Information</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      

      <div class="collapse navbar-collapse" id="navbarsExample01">
        <ul class="navbar-nav me-auto mb-2">
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="#">Members</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="#">Portfolio</a>
          </li>
        </ul>
        <form role="search">
          <input class="form-control" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
{% endblock %}

birds_eye/clubs/templates/clubs/group_list.html
{% extends "clubs/club_base.html" %}

{% block pregroup%}
<div class="col-md-4">
    <div class="container">
        {% if user.is_authenticated %}
        <h2>
            Welcome back!
            <a href="#">
            {% comment %} <a href="{% url 'posts:for_user' username=user.username %}"> {% endcomment %}
                @{{ user.username }}
            </a>
        </h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>

    {% if user.is_authenticated %}
    <a href="{% url 'djf_surveys:index' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign">Create new Group!</span>
    </a>
    {% endif %}

</div>
<hr>
{% endblock %}
{% block group_content %}
<hr>
{% comment %} Complete making group display. {% endcomment %}
<p></p>
<div class="col-md-8">
    <div class="container">
        {% for club in object_list %}
        <a class="list-group-item" href="{% url 'clubs:single' slug=club.slug %}">
            <h3 class="title list-group-item-heading">{{ club.name }}</h3>
            <span>{{ club.slogan|safe }}</span>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock %}

birds_eye/events/templates/events/event_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% block pregroup %}
    {% endblock %}
    {% block group_content %}
    {% endblock %}
    {% block postgroup %}
    {% endblock %}
</div>
{% endblock %}

birds_eye/events/templates/events/event_list.html
{% extends "events/event_base.html" %}

{% block pregroup %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Sorry but this page is currently unavailable.</h1>
        <p class="col-md-8 fs-4">
            We are working our best to give you the best experience! This page will be fully
            functional in the future.
        </p>
    </div>
</div>
{% endblock %}

birds_eye/feeds/templates/feeds/feed_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% block pregroup %}
    {% endblock %}
    {% block group_content %}
    {% endblock %}
    {% block postgroup %}
    {% endblock %}
</div>
{% endblock %}

birds_eye/feeds/templates/feeds/feed_list.html
{% extends "feeds/feed_base.html" %}

{% block pregroup %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Sorry but this page is currently unavailable.</h1>
        <p class="col-md-8 fs-4">
            We are working our best to give you the best experience! This page will be fully
            functional in the future.
        </p>
    </div>
</div>
{% endblock %}

birds_eye/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Birds Eye</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    </head>
    <body>

        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-light">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Birds Eye</span>
                        </a>
                        {% if user.is_authenticated %}
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                            <li>
                                <a href="{% url 'events:entire' %}" class="nav-link align-middle px-0 text-secondary">
                                    <i class="fs-4 bi-calendar3"></i> <span class="ms-1 d-none d-sm-inline">Calendar</span> </a>
                            </li>
                            <li>
                                <a href="{% url 'feeds:all' %}" class="nav-link align-middle px-0 text-secondary">
                                    <i class="fs-4 bi-activity"></i> <span class="ms-1 d-none d-sm-inline">Feed</span> </a>
                            </li>
                            <li>
                                <a href="{% url 'clubs:all' %}" class="nav-link align-middle px-0 text-secondary">
                                    <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Clubs</span> </a>
                            </li>
                        </ul>
                        <hr>
                        <div class="dropdown pb-4">
                            <a href="#" class="d-flex align-items-center text-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fs-4 bi-person-circle"></i>
                                <!-- <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">-->
                                <span class="d-none d-sm-inline mx-1">{{ user.username }}</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                                <!-- <li><a class="dropdown-item" href="#">Settings</a></li> -->
                                {% comment %} <li><a class="dropdown-item" href="#">Profile</a></li> {% endcomment %}
                                {% comment %} <li>
                                    <hr class="dropdown-divider">
                                </li> {% endcomment %}
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign out</a></li>
                            </ul>
                        </div>
                        {% else %}
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                            <li>
                                <a href="{% url 'events:entire' %}" class="nav-link align-middle px-0 text-secondary">
                                    <i class="fs-4 bi-calendar3"></i> <span class="ms-1 d-none d-sm-inline">Calendar</span> </a>
                            </li>
                            <li>
                                <a href="{% url 'feeds:all' %}" class="nav-link align-middle px-0 text-secondary">
                                    <i class="fs-4 bi-activity"></i> <span class="ms-1 d-none d-sm-inline">Feed</span> </a>
                            </li>
                            <li>
                                <a href="{% url 'clubs:all' %}" class="nav-link align-middle px-0 text-secondary">
                                    <i class="fs-4 bi-collection"></i> <span class="ms-1 d-none d-sm-inline">Clubs</span> </a>
                            </li>
                        </ul>
                        <hr>
                        <div class="dropdown pb-4">
                            <a href="#" class="d-flex align-items-center text-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fs-4 bi-person-circle"></i>
                                <!-- <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">-->
                                <span class="d-none d-sm-inline mx-1">User</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                                <!-- <li><a class="dropdown-item" href="#">Settings</a></li> -->
                                <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Log In</a></li>
                            </ul>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col py-3">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

birds_eye/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="first">
    <h1>Welcome to Birds Eye!</h1>
    <p>This website is dedicated to helping out on organizing different clubs/organizations taking place in Dwight School Seoul</p>
</div>

{% endblock %}

birds_eye/templates/test.html
{% extends "base.html" %}

{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

birds_eye/templates/thanks.html
{% extends "base.html" %}

{% block content %}

<h1>Thank you for visiting, come back soon!</h1>
    
{% endblock %}